# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

set_conda_version <- function(conda_version) {
    invisible(.Call(`_rhumba_set_conda_version`, conda_version))
}

set_verbosity <- function(lvl) {
    invisible(.Call(`_rhumba_set_verbosity`, lvl))
}

set_root_prefix <- function(root_prefix) {
    invisible(.Call(`_rhumba_set_root_prefix`, root_prefix))
}

set_channels <- function(channels) {
    invisible(.Call(`_rhumba_set_channels`, channels))
}

set_opt <- function(option, value) {
    invisible(.Call(`_rhumba_set_opt`, option, value))
}

print_context <- function() {
    invisible(.Call(`_rhumba_print_context`))
}

install <- function(specs, create_env = FALSE) {
    invisible(.Call(`_rhumba_install`, specs, create_env))
}

